### ISSUE TITLE
gnome-3.18 files style ugly

### ISSUE THREAD

**Issue by jilen** [lucaciavatta/tear-theme#1]
![screenshot from 2016-03-03 13-18-27](https://cloud.githubusercontent.com/assets/546573/13485414/7218719e-e142-11e5-80d8-b2095fe799ab.png)

**Comment by lucaciavatta** [comment]
Hi! Did you put Tear Icons folder under '.icons' in your home and activate it with Gnome Tweak Tool?
Thx.

**Comment by jilen** [comment]
@lucaciavatta I mean left side panel
![screenshot from 2016-03-03 19-42-22](https://cloud.githubusercontent.com/assets/546573/13493272/1bf3cbf2-e178-11e5-85e3-df4c2c5983de.png)

**Comment by lucaciavatta** [comment]
So, sorry.
Actually, I designed it in that way.
![screenshot-20160303_131646](https://cloud.githubusercontent.com/assets/1382127/13494116/83d8de6e-e142-11e5-8fa9-47ff1b1a3911.png)
Maybe, do you have any nice suggestions?

**Comment by jilen** [comment]
@lucaciavatta I think we need padding between icon and left border

**Comment by lucaciavatta** [comment]
@jilen I did a little mod to follow your suggestion. Let me know if you like it.

![screenshot-20160304_091733](https://cloud.githubusercontent.com/assets/1382127/13521611/37ea1f10-e1ea-11e5-9abc-74f5c0c7e4b2.png)

Just added some code to **gtk-3.0>apps>gnome-applications.css**:
`NautilusWindow .sidebar-icon {
    padding-left: 10px;
    padding-right: 10px;
}`
You can modify the padding values to fit your needs.

**Comment by lucaciavatta** [comment]
I already updated the code on Github and you can download the new version too.

**Comment by jilen** [comment]
@lucaciavatta Cool

**Comment by lucaciavatta** [comment]
@jilen thx.
